# Generated by Django 6.0.2 on 2026-02-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('budget', models.FloatField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('travel_type', models.CharField(max_length=20)),
                ('group_size', models.IntegerField(default=1)),
                ('travel_scope', models.CharField(max_length=30)),
                ('num_days', models.IntegerField()),
                ('food_accommodation', models.CharField(max_length=20)),
                ('from_location', models.CharField(max_length=200)),
                ('travel_medium', models.CharField(max_length=50)),
                ('destination_styles', models.JSONField(default=list)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('ip_location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
